### ISSUE TITLE
GUI does not scale well to different window sizes

### ISSUE THREAD

**Issue by zhiayang** [AY2021S1-CS2103T-T10-3/tp#63]
Works ok at default size:
![2020-10-13-221630_918x567_scrot](https://user-images.githubusercontent.com/500236/95872978-07b38280-0da2-11eb-8af0-19a2cb3ae699.png)

Does not work when resized:
![2020-10-13-221746_1507x1012_scrot](https://user-images.githubusercontent.com/500236/95873010-100bbd80-0da2-11eb-8607-086040f64162.png)

I think you can use some `AnchorPanes` to pin each UI component to one of the edges, then resize accordingly @fall9x 

Can push to 1.3.

**Comment by fall9x** [comment]
Should I make the application non resizable instead? @zhiayang
