### ISSUE TITLE
GUI should not start on an empty pane

### ISSUE THREAD

**Issue by zhiayang** [AY2021S1-CS2103T-T10-3/tp#64]
I think the starting screen should either be the recipe or ingredient list, and not whatever we have right now (unless we plan to put stuff there).

feels weird to have to click on the tab bar to actually start doing stuff

**Comment by fall9x** [comment]
Should we only start with an empty pane if the recipe book is empty? Like maybe the empty pane can get a quick view of the command breakdown

**Comment by zhiayang** [comment]
hmm, yea that makes sense. but idk if we’re gonna put some sample data by default like AB3?

but ya either way i think should have some getting started text on that page, but maybe only the first launch bah

**Comment by Trav1sT** [comment]
Im sorry our recipes very cui. Quick view of the command breakdown sounds great.
